### ISSUE TITLE
RoR Control Emercy stop 

### ISSUE THREAD

**Issue by calberts** [msproul/AlpacaPi#25]
Hoi paul how are you 

I like to request an extra function for the RoR alpaca part which you created.
I need an extra API which is an Emercy stop of the roof movement.

if you have some time it would be handy to have that.

Also, i like to inform you that the software runs very stable for a long time.

Possible also handy is that you can display on the  web pages set up the compiled versions, which are running but that is a nice to have

Thanks in advance

Chris

**Comment by msproul** [comment]
Chris

I would be glad to help with this.  Please contact me direct with more details.  I am sorry that I did not respond sooner.
msproul -at- skychariot.com
Mark

**Comment by msproul** [comment]
I have done a lot of work with Chris and believe we can close this now

Mark
