### ISSUE TITLE
Alpaca management parameters

### ISSUE THREAD

**Issue by pchev** [msproul/AlpacaPi#29]
I remark the management API do not support the parameters  ClientID and ClientTransactionID.

The following URL:
http://127.0.0.1:6800/management/v1/description?ClientID=1&ClientTransactionID=2
return this error:
{
		"Device":"ManagementDriver",
		"Command":"description?ClientID=1&ClientTransactionID=2",
		"ClientTransactionID":2,
		"ServerTransactionID":2086,
		"ErrorNumber":1035,
		"ErrorMessage":"AlpacaPi:Unrecognized command:description?ClientID=1&ClientTransactionID=2: ProcessCommand_Common: 708"
}

Without the parameters it work fine.

This two parameters are defined in the Management API:
https://ascom-standards.org/api/?urls.primaryName=ASCOM%20Alpaca%20Management%20API

**Comment by msproul** [comment]
Patrick
Thanks for finding this and pointing it out.  It has been fixed in build #172 which I just pushed.
Mark

**Comment by pchev** [comment]
Thank you! I tested it work now.
