### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by testezt** [msproul/AlpacaPi#35]
./src/domedriver_ror_rpi.cpp:345:31: error: ‘kRelay_FlatScren’ was not declared in this scope
  345 |  relayOK  = RpiRelay_SetRelay(kRelay_FlatScren, onOffFlag);
      |                               ^~~~~~~~~~~~~~~~
./src/domedriver_ror_rpi.cpp: In member function ‘virtual TYPE_ASCOM_STATUS DomeDriverROR::GetAuxiliary(bool*)’:
./src/domedriver_ror_rpi.cpp:358:33: error: ‘kRelay_FlatScren’ was not declared in this scope
  358 |  *onOffFlag = RpiRelay_GetRelay(kRelay_FlatScren);
      |                                 ^~~~~~~~~~~~~~~~
make: *** [Makefile:4459: Objectfiles/domedriver_ror_rpi.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by msproul** [comment]
Thanks for catching this, I have it fixed now.

Mark
