### ISSUE TITLE
Readoutmode & Sensortype

### ISSUE THREAD

**Issue by testezt** [msproul/AlpacaPi#36]
I'm not an expert about a raw image and also not sure if this is issue. But other than kImageType_RGB24, SensorType switched to kSensorType_Monochrome. Is kImageType_RAW16 & kSensorType_RGGB not possible for a color camera?

					if (newImageType == kImageType_RGB24)
					{
//						CONSOLE_DEBUG("Setting sensorType to kSensorType_Color");
						cCameraProp.SensorType	=	kSensorType_Color;
						printf("set SensorType =%d\n", cCameraProp.SensorType);
					}
					else
					{
//						CONSOLE_DEBUG("Setting sensorType to kSensorType_Monochrome");
						cCameraProp.SensorType	=	kSensorType_Monochrome;
						printf("set SensorType =%d\n", cCameraProp.SensorType);
					}

**Comment by testezt** [comment]
I don't think you change SensorType along with Readoutmode. For color camera, it is going to be messed up. I just test it with ASI mono and color cameras. This is sufficed.

TYPE_ASCOM_STATUS	CameraDriver::Put_Readoutmode(TYPE_GetPutRequestData *reqData, char *alpacaErrMsg)
{
TYPE_ASCOM_STATUS	alpacaErrCode	=	kASCOM_Err_Success;
int					mySocketFD;
bool				readOutFound;
char				readOutModeString[32];
int					alpacaReadOutModeIdx;
TYPE_IMAGE_TYPE		newImageType;

//	CONSOLE_DEBUG(__FUNCTION__);

	readOutFound		=	GetKeyWordArgument(	reqData->contentData,
												"ReadoutMode",
												readOutModeString,
												(sizeof(readOutModeString) -1));

//	CONSOLE_DEBUG_W_STR("readOutModeString\t\t=", readOutModeString);

	if (readOutFound)
	{
		if (isdigit(readOutModeString[0]))
		{
//			CONSOLE_DEBUG("Processing digit");
			alpacaReadOutModeIdx	=	atoi(readOutModeString);
//			CONSOLE_DEBUG_W_NUM("alpacaReadOutModeIdx\t=", alpacaReadOutModeIdx);

			//*	is the new image mode index within range
			if ((alpacaReadOutModeIdx >= 0) && (alpacaReadOutModeIdx < kMaxReadOutModes))
			{
				//*	is this readout mode valid for this camera
				if (cCameraProp.ReadOutModes[alpacaReadOutModeIdx].valid)
				{
					newImageType	=	(TYPE_IMAGE_TYPE)cCameraProp.ReadOutModes[alpacaReadOutModeIdx].internalImageType;
//					CONSOLE_DEBUG_W_NUM("newImageType\t\t=", newImageType);
					alpacaErrCode	=	SetImageType(newImageType);
					
					//*	now update the sensor type based on the image type
					/*if (newImageType == kImageType_RGB24)
					{
//						CONSOLE_DEBUG("Setting sensorType to kSensorType_Color");
						cCameraProp.SensorType	=	kSensorType_Color;
						printf("set SensorType =%d\n", cCameraProp.SensorType);
					}
					else
					{
//						CONSOLE_DEBUG("Setting sensorType to kSensorType_Monochrome");
						cCameraProp.SensorType	=	kSensorType_Monochrome;
						printf("set SensorType =%d\n", cCameraProp.SensorType);
					}*/
				}
				else
				{
					alpacaErrCode			=	kASCOM_Err_InvalidValue;
					reqData->httpRetCode	=	400;
					GENERATE_ALPACAPI_ERRMSG(alpacaErrMsg, "INVALID alpacaReadOutModeIdx");
					CONSOLE_DEBUG_W_NUM("INVALID alpacaReadOutModeIdx\t=", alpacaReadOutModeIdx);
				}
			}
			else
			{
				alpacaErrCode			=	kASCOM_Err_InvalidValue;
				reqData->httpRetCode	=	400;
				GENERATE_ALPACAPI_ERRMSG(alpacaErrMsg, "Value out of range");
				CONSOLE_DEBUG(alpacaErrMsg);
			}
		}
		else
		{
			CONSOLE_DEBUG("Processing string");
			alpacaErrCode	=	SetImageType(readOutModeString);
		}

		if (alpacaErrCode != kASCOM_Err_Success)
		{
			CONSOLE_DEBUG_W_NUM("alpacaErrCode\t=",		alpacaErrCode);
			CONSOLE_DEBUG_W_STR("cLastCameraErrMsg\t=",	cLastCameraErrMsg);
			GENERATE_ALPACAPI_ERRMSG(alpacaErrMsg, cLastCameraErrMsg);
		}
	}
	else
	{
		alpacaErrCode			=	kASCOM_Err_InvalidValue;
		reqData->httpRetCode	=	400;
		GENERATE_ALPACAPI_ERRMSG(alpacaErrMsg, "Mode not specified");
		CONSOLE_DEBUG(alpacaErrMsg);
	}
	mySocketFD	=	reqData->socket;

	cBytesWrittenForThisCmd	+=	JsonResponse_Add_Int32(	mySocketFD,
									reqData->jsonTextBuffer,
									kMaxJsonBuffLen,
									"Value",
									0,
									INCLUDE_COMMA);
	return(alpacaErrCode);
}

**Comment by msproul** [comment]
I have added your fixes to the main build, you can search for EZT to find them.
